// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/proto/msg_edit/msg_edit.proto

package msg_edit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息編輯客戶端信息
type MessageEditClientInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      int32                  `protobuf:"varint,1,opt,name=platform,proto3" json:"platform,omitempty"`                      // 編輯平台 ID
	AppVersion    string                 `protobuf:"bytes,2,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"` // APP 版本
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`    // IP 地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEditClientInfo) Reset() {
	*x = MessageEditClientInfo{}
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEditClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEditClientInfo) ProtoMessage() {}

func (x *MessageEditClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEditClientInfo.ProtoReflect.Descriptor instead.
func (*MessageEditClientInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_edit_msg_edit_proto_rawDescGZIP(), []int{0}
}

func (x *MessageEditClientInfo) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *MessageEditClientInfo) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *MessageEditClientInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

// 編輯消息請求
type EditMessageReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 會話 ID
	Seq            int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`                                            // 消息序列號
	NewContent     string                 `protobuf:"bytes,3,opt,name=new_content,json=newContent,proto3" json:"new_content,omitempty"`             // 新的消息內容
	EditReason     string                 `protobuf:"bytes,4,opt,name=edit_reason,json=editReason,proto3" json:"edit_reason,omitempty"`             // 編輯原因（可選）
	ClientInfo     *MessageEditClientInfo `protobuf:"bytes,5,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`             // 客戶端信息
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EditMessageReq) Reset() {
	*x = EditMessageReq{}
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMessageReq) ProtoMessage() {}

func (x *EditMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMessageReq.ProtoReflect.Descriptor instead.
func (*EditMessageReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_edit_msg_edit_proto_rawDescGZIP(), []int{1}
}

func (x *EditMessageReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *EditMessageReq) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *EditMessageReq) GetNewContent() string {
	if x != nil {
		return x.NewContent
	}
	return ""
}

func (x *EditMessageReq) GetEditReason() string {
	if x != nil {
		return x.EditReason
	}
	return ""
}

func (x *EditMessageReq) GetClientInfo() *MessageEditClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

// 編輯消息響應
type EditMessageResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                    // 是否成功
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                     // 響應消息
	UpdatedMessage *EditedMessageInfo     `protobuf:"bytes,3,opt,name=updated_message,json=updatedMessage,proto3" json:"updated_message,omitempty"` // 更新後的消息信息
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EditMessageResp) Reset() {
	*x = EditMessageResp{}
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMessageResp) ProtoMessage() {}

func (x *EditMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMessageResp.ProtoReflect.Descriptor instead.
func (*EditMessageResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_edit_msg_edit_proto_rawDescGZIP(), []int{2}
}

func (x *EditMessageResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EditMessageResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EditMessageResp) GetUpdatedMessage() *EditedMessageInfo {
	if x != nil {
		return x.UpdatedMessage
	}
	return nil
}

// 編輯後的消息信息
type EditedMessageInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`     // 會話 ID
	Seq            int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`                                                // 消息序列號
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                             // 編輯用戶 ID
	IsEdited       bool                   `protobuf:"varint,4,opt,name=is_edited,json=isEdited,proto3" json:"is_edited,omitempty"`                      // 是否已編輯
	EditCount      int32                  `protobuf:"varint,5,opt,name=edit_count,json=editCount,proto3" json:"edit_count,omitempty"`                   // 編輯次數
	EditTime       int64                  `protobuf:"varint,6,opt,name=edit_time,json=editTime,proto3" json:"edit_time,omitempty"`                      // 編輯時間（毫秒時間戳）
	LastEditUserId string                 `protobuf:"bytes,7,opt,name=last_edit_user_id,json=lastEditUserId,proto3" json:"last_edit_user_id,omitempty"` // 最後編輯者 ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EditedMessageInfo) Reset() {
	*x = EditedMessageInfo{}
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditedMessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditedMessageInfo) ProtoMessage() {}

func (x *EditedMessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditedMessageInfo.ProtoReflect.Descriptor instead.
func (*EditedMessageInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_edit_msg_edit_proto_rawDescGZIP(), []int{3}
}

func (x *EditedMessageInfo) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *EditedMessageInfo) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *EditedMessageInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EditedMessageInfo) GetIsEdited() bool {
	if x != nil {
		return x.IsEdited
	}
	return false
}

func (x *EditedMessageInfo) GetEditCount() int32 {
	if x != nil {
		return x.EditCount
	}
	return 0
}

func (x *EditedMessageInfo) GetEditTime() int64 {
	if x != nil {
		return x.EditTime
	}
	return 0
}

func (x *EditedMessageInfo) GetLastEditUserId() string {
	if x != nil {
		return x.LastEditUserId
	}
	return ""
}

// 消息編輯記錄
type MessageEditRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EditId        string                 `protobuf:"bytes,1,opt,name=edit_id,json=editId,proto3" json:"edit_id,omitempty"`                     // 編輯記錄 ID
	EditTime      int64                  `protobuf:"varint,2,opt,name=edit_time,json=editTime,proto3" json:"edit_time,omitempty"`              // 編輯時間
	EditUserId    string                 `protobuf:"bytes,3,opt,name=edit_user_id,json=editUserId,proto3" json:"edit_user_id,omitempty"`       // 編輯者用戶 ID
	EditUserName  string                 `protobuf:"bytes,4,opt,name=edit_user_name,json=editUserName,proto3" json:"edit_user_name,omitempty"` // 編輯者用戶名
	OldContent    string                 `protobuf:"bytes,5,opt,name=old_content,json=oldContent,proto3" json:"old_content,omitempty"`         // 編輯前內容
	NewContent    string                 `protobuf:"bytes,6,opt,name=new_content,json=newContent,proto3" json:"new_content,omitempty"`         // 編輯後內容
	EditReason    string                 `protobuf:"bytes,7,opt,name=edit_reason,json=editReason,proto3" json:"edit_reason,omitempty"`         // 編輯原因
	ClientInfo    *MessageEditClientInfo `protobuf:"bytes,8,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`         // 客戶端信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEditRecord) Reset() {
	*x = MessageEditRecord{}
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEditRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEditRecord) ProtoMessage() {}

func (x *MessageEditRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEditRecord.ProtoReflect.Descriptor instead.
func (*MessageEditRecord) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_edit_msg_edit_proto_rawDescGZIP(), []int{4}
}

func (x *MessageEditRecord) GetEditId() string {
	if x != nil {
		return x.EditId
	}
	return ""
}

func (x *MessageEditRecord) GetEditTime() int64 {
	if x != nil {
		return x.EditTime
	}
	return 0
}

func (x *MessageEditRecord) GetEditUserId() string {
	if x != nil {
		return x.EditUserId
	}
	return ""
}

func (x *MessageEditRecord) GetEditUserName() string {
	if x != nil {
		return x.EditUserName
	}
	return ""
}

func (x *MessageEditRecord) GetOldContent() string {
	if x != nil {
		return x.OldContent
	}
	return ""
}

func (x *MessageEditRecord) GetNewContent() string {
	if x != nil {
		return x.NewContent
	}
	return ""
}

func (x *MessageEditRecord) GetEditReason() string {
	if x != nil {
		return x.EditReason
	}
	return ""
}

func (x *MessageEditRecord) GetClientInfo() *MessageEditClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

// 獲取編輯歷史請求
type GetMessageEditHistoryReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 會話 ID
	Seq            int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`                                            // 消息序列號
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMessageEditHistoryReq) Reset() {
	*x = GetMessageEditHistoryReq{}
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageEditHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageEditHistoryReq) ProtoMessage() {}

func (x *GetMessageEditHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageEditHistoryReq.ProtoReflect.Descriptor instead.
func (*GetMessageEditHistoryReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_edit_msg_edit_proto_rawDescGZIP(), []int{5}
}

func (x *GetMessageEditHistoryReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetMessageEditHistoryReq) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// 獲取編輯歷史響應
type GetMessageEditHistoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                           // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                            // 響應消息
	EditHistory   []*MessageEditRecord   `protobuf:"bytes,3,rep,name=edit_history,json=editHistory,proto3" json:"edit_history,omitempty"` // 編輯歷史記錄
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageEditHistoryResp) Reset() {
	*x = GetMessageEditHistoryResp{}
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageEditHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageEditHistoryResp) ProtoMessage() {}

func (x *GetMessageEditHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageEditHistoryResp.ProtoReflect.Descriptor instead.
func (*GetMessageEditHistoryResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_edit_msg_edit_proto_rawDescGZIP(), []int{6}
}

func (x *GetMessageEditHistoryResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetMessageEditHistoryResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMessageEditHistoryResp) GetEditHistory() []*MessageEditRecord {
	if x != nil {
		return x.EditHistory
	}
	return nil
}

// 驗證編輯權限請求
type ValidateEditPermissionReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 會話 ID
	Seq            int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`                                            // 消息序列號
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateEditPermissionReq) Reset() {
	*x = ValidateEditPermissionReq{}
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateEditPermissionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateEditPermissionReq) ProtoMessage() {}

func (x *ValidateEditPermissionReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateEditPermissionReq.ProtoReflect.Descriptor instead.
func (*ValidateEditPermissionReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_edit_msg_edit_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateEditPermissionReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ValidateEditPermissionReq) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// 驗證編輯權限響應
type ValidateEditPermissionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 響應消息
	Data          *PermissionResult      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`        // 權限驗證結果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateEditPermissionResp) Reset() {
	*x = ValidateEditPermissionResp{}
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateEditPermissionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateEditPermissionResp) ProtoMessage() {}

func (x *ValidateEditPermissionResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateEditPermissionResp.ProtoReflect.Descriptor instead.
func (*ValidateEditPermissionResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_edit_msg_edit_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateEditPermissionResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ValidateEditPermissionResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidateEditPermissionResp) GetData() *PermissionResult {
	if x != nil {
		return x.Data
	}
	return nil
}

// 權限驗證結果
type PermissionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanEdit       bool                   `protobuf:"varint,1,opt,name=can_edit,json=canEdit,proto3" json:"can_edit,omitempty"`                     // 是否可以編輯
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                       // 不能編輯的原因（如果 can_edit 為 false）
	TimeRemaining int64                  `protobuf:"varint,3,opt,name=time_remaining,json=timeRemaining,proto3" json:"time_remaining,omitempty"`   // 剩餘編輯時間（秒）
	EditCountLeft int32                  `protobuf:"varint,4,opt,name=edit_count_left,json=editCountLeft,proto3" json:"edit_count_left,omitempty"` // 剩餘編輯次數
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionResult) Reset() {
	*x = PermissionResult{}
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionResult) ProtoMessage() {}

func (x *PermissionResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionResult.ProtoReflect.Descriptor instead.
func (*PermissionResult) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_edit_msg_edit_proto_rawDescGZIP(), []int{9}
}

func (x *PermissionResult) GetCanEdit() bool {
	if x != nil {
		return x.CanEdit
	}
	return false
}

func (x *PermissionResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PermissionResult) GetTimeRemaining() int64 {
	if x != nil {
		return x.TimeRemaining
	}
	return 0
}

func (x *PermissionResult) GetEditCountLeft() int32 {
	if x != nil {
		return x.EditCountLeft
	}
	return 0
}

// 獲取可編輯消息請求
type GetEditableMessagesReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 會話 ID
	PageNumber     int32                  `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`            // 頁碼
	ShowNumber     int32                  `protobuf:"varint,3,opt,name=show_number,json=showNumber,proto3" json:"show_number,omitempty"`            // 每頁數量
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetEditableMessagesReq) Reset() {
	*x = GetEditableMessagesReq{}
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEditableMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEditableMessagesReq) ProtoMessage() {}

func (x *GetEditableMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEditableMessagesReq.ProtoReflect.Descriptor instead.
func (*GetEditableMessagesReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_edit_msg_edit_proto_rawDescGZIP(), []int{10}
}

func (x *GetEditableMessagesReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetEditableMessagesReq) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *GetEditableMessagesReq) GetShowNumber() int32 {
	if x != nil {
		return x.ShowNumber
	}
	return 0
}

// 可編輯消息信息
type EditableMessageInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Seq             int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`                                                // 消息序列號
	Content         string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                         // 消息內容
	ContentType     int32                  `protobuf:"varint,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`             // 內容類型
	SendTime        int64                  `protobuf:"varint,4,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`                      // 發送時間
	IsEdited        bool                   `protobuf:"varint,5,opt,name=is_edited,json=isEdited,proto3" json:"is_edited,omitempty"`                      // 是否已編輯
	EditCount       int32                  `protobuf:"varint,6,opt,name=edit_count,json=editCount,proto3" json:"edit_count,omitempty"`                   // 編輯次數
	LastEditTime    int64                  `protobuf:"varint,7,opt,name=last_edit_time,json=lastEditTime,proto3" json:"last_edit_time,omitempty"`        // 最後編輯時間
	LastEditUserId  string                 `protobuf:"bytes,8,opt,name=last_edit_user_id,json=lastEditUserId,proto3" json:"last_edit_user_id,omitempty"` // 最後編輯者 ID
	OriginalContent string                 `protobuf:"bytes,9,opt,name=original_content,json=originalContent,proto3" json:"original_content,omitempty"`  // 原始內容
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EditableMessageInfo) Reset() {
	*x = EditableMessageInfo{}
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditableMessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditableMessageInfo) ProtoMessage() {}

func (x *EditableMessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditableMessageInfo.ProtoReflect.Descriptor instead.
func (*EditableMessageInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_edit_msg_edit_proto_rawDescGZIP(), []int{11}
}

func (x *EditableMessageInfo) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *EditableMessageInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EditableMessageInfo) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *EditableMessageInfo) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *EditableMessageInfo) GetIsEdited() bool {
	if x != nil {
		return x.IsEdited
	}
	return false
}

func (x *EditableMessageInfo) GetEditCount() int32 {
	if x != nil {
		return x.EditCount
	}
	return 0
}

func (x *EditableMessageInfo) GetLastEditTime() int64 {
	if x != nil {
		return x.LastEditTime
	}
	return 0
}

func (x *EditableMessageInfo) GetLastEditUserId() string {
	if x != nil {
		return x.LastEditUserId
	}
	return ""
}

func (x *EditableMessageInfo) GetOriginalContent() string {
	if x != nil {
		return x.OriginalContent
	}
	return ""
}

// 分頁信息
type PaginationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNumber    int32                  `protobuf:"varint,1,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"` // 當前頁碼
	ShowNumber    int32                  `protobuf:"varint,2,opt,name=show_number,json=showNumber,proto3" json:"show_number,omitempty"` // 每頁數量
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`                             // 總數量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationInfo) Reset() {
	*x = PaginationInfo{}
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationInfo) ProtoMessage() {}

func (x *PaginationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationInfo.ProtoReflect.Descriptor instead.
func (*PaginationInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_edit_msg_edit_proto_rawDescGZIP(), []int{12}
}

func (x *PaginationInfo) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *PaginationInfo) GetShowNumber() int32 {
	if x != nil {
		return x.ShowNumber
	}
	return 0
}

func (x *PaginationInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 獲取可編輯消息響應
type GetEditableMessagesResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                    // 是否成功
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                     // 響應消息
	ConversationId string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 會話 ID
	Messages       []*EditableMessageInfo `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`                                   // 可編輯消息列表
	Pagination     *PaginationInfo        `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`                               // 分頁信息
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetEditableMessagesResp) Reset() {
	*x = GetEditableMessagesResp{}
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEditableMessagesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEditableMessagesResp) ProtoMessage() {}

func (x *GetEditableMessagesResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEditableMessagesResp.ProtoReflect.Descriptor instead.
func (*GetEditableMessagesResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_edit_msg_edit_proto_rawDescGZIP(), []int{13}
}

func (x *GetEditableMessagesResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetEditableMessagesResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetEditableMessagesResp) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetEditableMessagesResp) GetMessages() []*EditableMessageInfo {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetEditableMessagesResp) GetPagination() *PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 編輯通知數據
type EditNotificationData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NotificationType string                 `protobuf:"bytes,1,opt,name=notification_type,json=notificationType,proto3" json:"notification_type,omitempty"` // 通知類型（messageEdit）
	ConversationId   string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`       // 會話 ID
	Seq              int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`                                                  // 消息序列號
	EditTime         int64                  `protobuf:"varint,4,opt,name=edit_time,json=editTime,proto3" json:"edit_time,omitempty"`                        // 編輯時間
	EditorUserId     string                 `protobuf:"bytes,5,opt,name=editor_user_id,json=editorUserId,proto3" json:"editor_user_id,omitempty"`           // 編輯者用戶 ID
	NewContent       string                 `protobuf:"bytes,6,opt,name=new_content,json=newContent,proto3" json:"new_content,omitempty"`                   // 新內容
	IsEdited         bool                   `protobuf:"varint,7,opt,name=is_edited,json=isEdited,proto3" json:"is_edited,omitempty"`                        // 是否已編輯
	EditCount        int32                  `protobuf:"varint,8,opt,name=edit_count,json=editCount,proto3" json:"edit_count,omitempty"`                     // 編輯次數
	OriginalSender   string                 `protobuf:"bytes,9,opt,name=original_sender,json=originalSender,proto3" json:"original_sender,omitempty"`       // 原始發送者 ID
	MsgType          int32                  `protobuf:"varint,10,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`                          // 消息類型
	ClientMsgId      string                 `protobuf:"bytes,11,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`             // 客戶端消息 ID
	ServerMsgId      string                 `protobuf:"bytes,12,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`             // 服務器消息 ID
	CreateTime       int64                  `protobuf:"varint,13,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`                 // 創建時間
	SendTime         int64                  `protobuf:"varint,14,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`                       // 發送時間
	SessionType      int32                  `protobuf:"varint,15,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"`              // 會話類型
	UpdatedMessage   *EditedMessageInfo     `protobuf:"bytes,16,opt,name=updated_message,json=updatedMessage,proto3" json:"updated_message,omitempty"`      // 完整的更新後消息數據
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EditNotificationData) Reset() {
	*x = EditNotificationData{}
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditNotificationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditNotificationData) ProtoMessage() {}

func (x *EditNotificationData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_edit_msg_edit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditNotificationData.ProtoReflect.Descriptor instead.
func (*EditNotificationData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_edit_msg_edit_proto_rawDescGZIP(), []int{14}
}

func (x *EditNotificationData) GetNotificationType() string {
	if x != nil {
		return x.NotificationType
	}
	return ""
}

func (x *EditNotificationData) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *EditNotificationData) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *EditNotificationData) GetEditTime() int64 {
	if x != nil {
		return x.EditTime
	}
	return 0
}

func (x *EditNotificationData) GetEditorUserId() string {
	if x != nil {
		return x.EditorUserId
	}
	return ""
}

func (x *EditNotificationData) GetNewContent() string {
	if x != nil {
		return x.NewContent
	}
	return ""
}

func (x *EditNotificationData) GetIsEdited() bool {
	if x != nil {
		return x.IsEdited
	}
	return false
}

func (x *EditNotificationData) GetEditCount() int32 {
	if x != nil {
		return x.EditCount
	}
	return 0
}

func (x *EditNotificationData) GetOriginalSender() string {
	if x != nil {
		return x.OriginalSender
	}
	return ""
}

func (x *EditNotificationData) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *EditNotificationData) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *EditNotificationData) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *EditNotificationData) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *EditNotificationData) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *EditNotificationData) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *EditNotificationData) GetUpdatedMessage() *EditedMessageInfo {
	if x != nil {
		return x.UpdatedMessage
	}
	return nil
}

var File_pkg_proto_msg_edit_msg_edit_proto protoreflect.FileDescriptor

const file_pkg_proto_msg_edit_msg_edit_proto_rawDesc = "" +
	"\n" +
	"!pkg/proto/msg_edit/msg_edit.proto\x12\x0fopenim.msg.edit\"s\n" +
	"\x15MessageEditClientInfo\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\x05R\bplatform\x12\x1f\n" +
	"\vapp_version\x18\x02 \x01(\tR\n" +
	"appVersion\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\"\xd6\x01\n" +
	"\x0eEditMessageReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x1f\n" +
	"\vnew_content\x18\x03 \x01(\tR\n" +
	"newContent\x12\x1f\n" +
	"\vedit_reason\x18\x04 \x01(\tR\n" +
	"editReason\x12G\n" +
	"\vclient_info\x18\x05 \x01(\v2&.openim.msg.edit.MessageEditClientInfoR\n" +
	"clientInfo\"\x92\x01\n" +
	"\x0fEditMessageResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12K\n" +
	"\x0fupdated_message\x18\x03 \x01(\v2\".openim.msg.edit.EditedMessageInfoR\x0eupdatedMessage\"\xeb\x01\n" +
	"\x11EditedMessageInfo\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tis_edited\x18\x04 \x01(\bR\bisEdited\x12\x1d\n" +
	"\n" +
	"edit_count\x18\x05 \x01(\x05R\teditCount\x12\x1b\n" +
	"\tedit_time\x18\x06 \x01(\x03R\beditTime\x12)\n" +
	"\x11last_edit_user_id\x18\a \x01(\tR\x0elastEditUserId\"\xbd\x02\n" +
	"\x11MessageEditRecord\x12\x17\n" +
	"\aedit_id\x18\x01 \x01(\tR\x06editId\x12\x1b\n" +
	"\tedit_time\x18\x02 \x01(\x03R\beditTime\x12 \n" +
	"\fedit_user_id\x18\x03 \x01(\tR\n" +
	"editUserId\x12$\n" +
	"\x0eedit_user_name\x18\x04 \x01(\tR\feditUserName\x12\x1f\n" +
	"\vold_content\x18\x05 \x01(\tR\n" +
	"oldContent\x12\x1f\n" +
	"\vnew_content\x18\x06 \x01(\tR\n" +
	"newContent\x12\x1f\n" +
	"\vedit_reason\x18\a \x01(\tR\n" +
	"editReason\x12G\n" +
	"\vclient_info\x18\b \x01(\v2&.openim.msg.edit.MessageEditClientInfoR\n" +
	"clientInfo\"U\n" +
	"\x18GetMessageEditHistoryReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\"\x96\x01\n" +
	"\x19GetMessageEditHistoryResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12E\n" +
	"\fedit_history\x18\x03 \x03(\v2\".openim.msg.edit.MessageEditRecordR\veditHistory\"V\n" +
	"\x19ValidateEditPermissionReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\"\x87\x01\n" +
	"\x1aValidateEditPermissionResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\x04data\x18\x03 \x01(\v2!.openim.msg.edit.PermissionResultR\x04data\"\x94\x01\n" +
	"\x10PermissionResult\x12\x19\n" +
	"\bcan_edit\x18\x01 \x01(\bR\acanEdit\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12%\n" +
	"\x0etime_remaining\x18\x03 \x01(\x03R\rtimeRemaining\x12&\n" +
	"\x0fedit_count_left\x18\x04 \x01(\x05R\reditCountLeft\"\x83\x01\n" +
	"\x16GetEditableMessagesReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1f\n" +
	"\vpage_number\x18\x02 \x01(\x05R\n" +
	"pageNumber\x12\x1f\n" +
	"\vshow_number\x18\x03 \x01(\x05R\n" +
	"showNumber\"\xb9\x02\n" +
	"\x13EditableMessageInfo\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\x05R\vcontentType\x12\x1b\n" +
	"\tsend_time\x18\x04 \x01(\x03R\bsendTime\x12\x1b\n" +
	"\tis_edited\x18\x05 \x01(\bR\bisEdited\x12\x1d\n" +
	"\n" +
	"edit_count\x18\x06 \x01(\x05R\teditCount\x12$\n" +
	"\x0elast_edit_time\x18\a \x01(\x03R\flastEditTime\x12)\n" +
	"\x11last_edit_user_id\x18\b \x01(\tR\x0elastEditUserId\x12)\n" +
	"\x10original_content\x18\t \x01(\tR\x0foriginalContent\"h\n" +
	"\x0ePaginationInfo\x12\x1f\n" +
	"\vpage_number\x18\x01 \x01(\x05R\n" +
	"pageNumber\x12\x1f\n" +
	"\vshow_number\x18\x02 \x01(\x05R\n" +
	"showNumber\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"\xf9\x01\n" +
	"\x17GetEditableMessagesResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12@\n" +
	"\bmessages\x18\x04 \x03(\v2$.openim.msg.edit.EditableMessageInfoR\bmessages\x12?\n" +
	"\n" +
	"pagination\x18\x05 \x01(\v2\x1f.openim.msg.edit.PaginationInfoR\n" +
	"pagination\"\xd8\x04\n" +
	"\x14EditNotificationData\x12+\n" +
	"\x11notification_type\x18\x01 \x01(\tR\x10notificationType\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12\x1b\n" +
	"\tedit_time\x18\x04 \x01(\x03R\beditTime\x12$\n" +
	"\x0eeditor_user_id\x18\x05 \x01(\tR\feditorUserId\x12\x1f\n" +
	"\vnew_content\x18\x06 \x01(\tR\n" +
	"newContent\x12\x1b\n" +
	"\tis_edited\x18\a \x01(\bR\bisEdited\x12\x1d\n" +
	"\n" +
	"edit_count\x18\b \x01(\x05R\teditCount\x12'\n" +
	"\x0foriginal_sender\x18\t \x01(\tR\x0eoriginalSender\x12\x19\n" +
	"\bmsg_type\x18\n" +
	" \x01(\x05R\amsgType\x12\"\n" +
	"\rclient_msg_id\x18\v \x01(\tR\vclientMsgId\x12\"\n" +
	"\rserver_msg_id\x18\f \x01(\tR\vserverMsgId\x12\x1f\n" +
	"\vcreate_time\x18\r \x01(\x03R\n" +
	"createTime\x12\x1b\n" +
	"\tsend_time\x18\x0e \x01(\x03R\bsendTime\x12!\n" +
	"\fsession_type\x18\x0f \x01(\x05R\vsessionType\x12K\n" +
	"\x0fupdated_message\x18\x10 \x01(\v2\".openim.msg.edit.EditedMessageInfoR\x0eupdatedMessage2\xb3\x03\n" +
	"\x12MessageEditService\x12P\n" +
	"\vEditMessage\x12\x1f.openim.msg.edit.EditMessageReq\x1a .openim.msg.edit.EditMessageResp\x12n\n" +
	"\x15GetMessageEditHistory\x12).openim.msg.edit.GetMessageEditHistoryReq\x1a*.openim.msg.edit.GetMessageEditHistoryResp\x12q\n" +
	"\x16ValidateEditPermission\x12*.openim.msg.edit.ValidateEditPermissionReq\x1a+.openim.msg.edit.ValidateEditPermissionResp\x12h\n" +
	"\x13GetEditableMessages\x12'.openim.msg.edit.GetEditableMessagesReq\x1a(.openim.msg.edit.GetEditableMessagesRespB;Z9github.com/openimsdk/open-im-server/v3/pkg/proto/msg_editb\x06proto3"

var (
	file_pkg_proto_msg_edit_msg_edit_proto_rawDescOnce sync.Once
	file_pkg_proto_msg_edit_msg_edit_proto_rawDescData []byte
)

func file_pkg_proto_msg_edit_msg_edit_proto_rawDescGZIP() []byte {
	file_pkg_proto_msg_edit_msg_edit_proto_rawDescOnce.Do(func() {
		file_pkg_proto_msg_edit_msg_edit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_msg_edit_msg_edit_proto_rawDesc), len(file_pkg_proto_msg_edit_msg_edit_proto_rawDesc)))
	})
	return file_pkg_proto_msg_edit_msg_edit_proto_rawDescData
}

var file_pkg_proto_msg_edit_msg_edit_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pkg_proto_msg_edit_msg_edit_proto_goTypes = []any{
	(*MessageEditClientInfo)(nil),      // 0: openim.msg.edit.MessageEditClientInfo
	(*EditMessageReq)(nil),             // 1: openim.msg.edit.EditMessageReq
	(*EditMessageResp)(nil),            // 2: openim.msg.edit.EditMessageResp
	(*EditedMessageInfo)(nil),          // 3: openim.msg.edit.EditedMessageInfo
	(*MessageEditRecord)(nil),          // 4: openim.msg.edit.MessageEditRecord
	(*GetMessageEditHistoryReq)(nil),   // 5: openim.msg.edit.GetMessageEditHistoryReq
	(*GetMessageEditHistoryResp)(nil),  // 6: openim.msg.edit.GetMessageEditHistoryResp
	(*ValidateEditPermissionReq)(nil),  // 7: openim.msg.edit.ValidateEditPermissionReq
	(*ValidateEditPermissionResp)(nil), // 8: openim.msg.edit.ValidateEditPermissionResp
	(*PermissionResult)(nil),           // 9: openim.msg.edit.PermissionResult
	(*GetEditableMessagesReq)(nil),     // 10: openim.msg.edit.GetEditableMessagesReq
	(*EditableMessageInfo)(nil),        // 11: openim.msg.edit.EditableMessageInfo
	(*PaginationInfo)(nil),             // 12: openim.msg.edit.PaginationInfo
	(*GetEditableMessagesResp)(nil),    // 13: openim.msg.edit.GetEditableMessagesResp
	(*EditNotificationData)(nil),       // 14: openim.msg.edit.EditNotificationData
}
var file_pkg_proto_msg_edit_msg_edit_proto_depIdxs = []int32{
	0,  // 0: openim.msg.edit.EditMessageReq.client_info:type_name -> openim.msg.edit.MessageEditClientInfo
	3,  // 1: openim.msg.edit.EditMessageResp.updated_message:type_name -> openim.msg.edit.EditedMessageInfo
	0,  // 2: openim.msg.edit.MessageEditRecord.client_info:type_name -> openim.msg.edit.MessageEditClientInfo
	4,  // 3: openim.msg.edit.GetMessageEditHistoryResp.edit_history:type_name -> openim.msg.edit.MessageEditRecord
	9,  // 4: openim.msg.edit.ValidateEditPermissionResp.data:type_name -> openim.msg.edit.PermissionResult
	11, // 5: openim.msg.edit.GetEditableMessagesResp.messages:type_name -> openim.msg.edit.EditableMessageInfo
	12, // 6: openim.msg.edit.GetEditableMessagesResp.pagination:type_name -> openim.msg.edit.PaginationInfo
	3,  // 7: openim.msg.edit.EditNotificationData.updated_message:type_name -> openim.msg.edit.EditedMessageInfo
	1,  // 8: openim.msg.edit.MessageEditService.EditMessage:input_type -> openim.msg.edit.EditMessageReq
	5,  // 9: openim.msg.edit.MessageEditService.GetMessageEditHistory:input_type -> openim.msg.edit.GetMessageEditHistoryReq
	7,  // 10: openim.msg.edit.MessageEditService.ValidateEditPermission:input_type -> openim.msg.edit.ValidateEditPermissionReq
	10, // 11: openim.msg.edit.MessageEditService.GetEditableMessages:input_type -> openim.msg.edit.GetEditableMessagesReq
	2,  // 12: openim.msg.edit.MessageEditService.EditMessage:output_type -> openim.msg.edit.EditMessageResp
	6,  // 13: openim.msg.edit.MessageEditService.GetMessageEditHistory:output_type -> openim.msg.edit.GetMessageEditHistoryResp
	8,  // 14: openim.msg.edit.MessageEditService.ValidateEditPermission:output_type -> openim.msg.edit.ValidateEditPermissionResp
	13, // 15: openim.msg.edit.MessageEditService.GetEditableMessages:output_type -> openim.msg.edit.GetEditableMessagesResp
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_proto_msg_edit_msg_edit_proto_init() }
func file_pkg_proto_msg_edit_msg_edit_proto_init() {
	if File_pkg_proto_msg_edit_msg_edit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_msg_edit_msg_edit_proto_rawDesc), len(file_pkg_proto_msg_edit_msg_edit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_msg_edit_msg_edit_proto_goTypes,
		DependencyIndexes: file_pkg_proto_msg_edit_msg_edit_proto_depIdxs,
		MessageInfos:      file_pkg_proto_msg_edit_msg_edit_proto_msgTypes,
	}.Build()
	File_pkg_proto_msg_edit_msg_edit_proto = out.File
	file_pkg_proto_msg_edit_msg_edit_proto_goTypes = nil
	file_pkg_proto_msg_edit_msg_edit_proto_depIdxs = nil
}
