// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: pkg/proto/msg_edit/msg_edit.proto

package msg_edit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageEditService_EditMessage_FullMethodName            = "/openim.msg.edit.MessageEditService/EditMessage"
	MessageEditService_GetMessageEditHistory_FullMethodName  = "/openim.msg.edit.MessageEditService/GetMessageEditHistory"
	MessageEditService_ValidateEditPermission_FullMethodName = "/openim.msg.edit.MessageEditService/ValidateEditPermission"
	MessageEditService_GetEditableMessages_FullMethodName    = "/openim.msg.edit.MessageEditService/GetEditableMessages"
)

// MessageEditServiceClient is the client API for MessageEditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 消息編輯服務定義
type MessageEditServiceClient interface {
	// 編輯消息
	EditMessage(ctx context.Context, in *EditMessageReq, opts ...grpc.CallOption) (*EditMessageResp, error)
	// 獲取消息編輯歷史
	GetMessageEditHistory(ctx context.Context, in *GetMessageEditHistoryReq, opts ...grpc.CallOption) (*GetMessageEditHistoryResp, error)
	// 驗證編輯權限
	ValidateEditPermission(ctx context.Context, in *ValidateEditPermissionReq, opts ...grpc.CallOption) (*ValidateEditPermissionResp, error)
	// 獲取可編輯消息列表
	GetEditableMessages(ctx context.Context, in *GetEditableMessagesReq, opts ...grpc.CallOption) (*GetEditableMessagesResp, error)
}

type messageEditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageEditServiceClient(cc grpc.ClientConnInterface) MessageEditServiceClient {
	return &messageEditServiceClient{cc}
}

func (c *messageEditServiceClient) EditMessage(ctx context.Context, in *EditMessageReq, opts ...grpc.CallOption) (*EditMessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditMessageResp)
	err := c.cc.Invoke(ctx, MessageEditService_EditMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageEditServiceClient) GetMessageEditHistory(ctx context.Context, in *GetMessageEditHistoryReq, opts ...grpc.CallOption) (*GetMessageEditHistoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageEditHistoryResp)
	err := c.cc.Invoke(ctx, MessageEditService_GetMessageEditHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageEditServiceClient) ValidateEditPermission(ctx context.Context, in *ValidateEditPermissionReq, opts ...grpc.CallOption) (*ValidateEditPermissionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateEditPermissionResp)
	err := c.cc.Invoke(ctx, MessageEditService_ValidateEditPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageEditServiceClient) GetEditableMessages(ctx context.Context, in *GetEditableMessagesReq, opts ...grpc.CallOption) (*GetEditableMessagesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEditableMessagesResp)
	err := c.cc.Invoke(ctx, MessageEditService_GetEditableMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageEditServiceServer is the server API for MessageEditService service.
// All implementations must embed UnimplementedMessageEditServiceServer
// for forward compatibility.
//
// 消息編輯服務定義
type MessageEditServiceServer interface {
	// 編輯消息
	EditMessage(context.Context, *EditMessageReq) (*EditMessageResp, error)
	// 獲取消息編輯歷史
	GetMessageEditHistory(context.Context, *GetMessageEditHistoryReq) (*GetMessageEditHistoryResp, error)
	// 驗證編輯權限
	ValidateEditPermission(context.Context, *ValidateEditPermissionReq) (*ValidateEditPermissionResp, error)
	// 獲取可編輯消息列表
	GetEditableMessages(context.Context, *GetEditableMessagesReq) (*GetEditableMessagesResp, error)
	mustEmbedUnimplementedMessageEditServiceServer()
}

// UnimplementedMessageEditServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageEditServiceServer struct{}

func (UnimplementedMessageEditServiceServer) EditMessage(context.Context, *EditMessageReq) (*EditMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditMessage not implemented")
}
func (UnimplementedMessageEditServiceServer) GetMessageEditHistory(context.Context, *GetMessageEditHistoryReq) (*GetMessageEditHistoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessageEditHistory not implemented")
}
func (UnimplementedMessageEditServiceServer) ValidateEditPermission(context.Context, *ValidateEditPermissionReq) (*ValidateEditPermissionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateEditPermission not implemented")
}
func (UnimplementedMessageEditServiceServer) GetEditableMessages(context.Context, *GetEditableMessagesReq) (*GetEditableMessagesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEditableMessages not implemented")
}
func (UnimplementedMessageEditServiceServer) mustEmbedUnimplementedMessageEditServiceServer() {}
func (UnimplementedMessageEditServiceServer) testEmbeddedByValue()                            {}

// UnsafeMessageEditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageEditServiceServer will
// result in compilation errors.
type UnsafeMessageEditServiceServer interface {
	mustEmbedUnimplementedMessageEditServiceServer()
}

func RegisterMessageEditServiceServer(s grpc.ServiceRegistrar, srv MessageEditServiceServer) {
	// If the following call pancis, it indicates UnimplementedMessageEditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageEditService_ServiceDesc, srv)
}

func _MessageEditService_EditMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageEditServiceServer).EditMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageEditService_EditMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageEditServiceServer).EditMessage(ctx, req.(*EditMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageEditService_GetMessageEditHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageEditHistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageEditServiceServer).GetMessageEditHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageEditService_GetMessageEditHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageEditServiceServer).GetMessageEditHistory(ctx, req.(*GetMessageEditHistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageEditService_ValidateEditPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateEditPermissionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageEditServiceServer).ValidateEditPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageEditService_ValidateEditPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageEditServiceServer).ValidateEditPermission(ctx, req.(*ValidateEditPermissionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageEditService_GetEditableMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEditableMessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageEditServiceServer).GetEditableMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageEditService_GetEditableMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageEditServiceServer).GetEditableMessages(ctx, req.(*GetEditableMessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageEditService_ServiceDesc is the grpc.ServiceDesc for MessageEditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageEditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openim.msg.edit.MessageEditService",
	HandlerType: (*MessageEditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EditMessage",
			Handler:    _MessageEditService_EditMessage_Handler,
		},
		{
			MethodName: "GetMessageEditHistory",
			Handler:    _MessageEditService_GetMessageEditHistory_Handler,
		},
		{
			MethodName: "ValidateEditPermission",
			Handler:    _MessageEditService_ValidateEditPermission_Handler,
		},
		{
			MethodName: "GetEditableMessages",
			Handler:    _MessageEditService_GetEditableMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/msg_edit/msg_edit.proto",
}
